// DFCMS Custom AI Sites — Shared Block Defaults
// Source of truth for block schemas across Edge Functions (chat-site-agent, god-provision-site)

// deno-lint-ignore no-explicit-any
export const BLOCK_DEFAULTS: Record<string, Record<string, any>> = {
  cinematic_hero: {
    title: "Twórca Filmowy",
    subtitle: "Director & Cinematographer",
    tagline: "Historie opowiadane światłem i ruchem.",
    video_url: "https://vimeo.com/76979871",
    video_provider: "vimeo",
    video_id: "76979871",
    showreel_url: "https://vimeo.com/76979871",
    cta_text: "Odtwórz Showreel",
    cta_secondary_text: "Zobacz Projekty",
    cta_secondary_target: "#projekty",
  },
  projects_grid: {
    heading: "Wybrane Realizacje",
    subheading: "Reklama · Teledyski · Formy Fabularne",
    feed_source: { type: "manual", handle: "", folder_id: "" },
    items: [
      {
        id: "p1",
        title: "Spot Komercyjny — Nowa Fala",
        category: "Commercial",
        role: "Reżyseria / Zdjęcia",
        video_url: "https://vimeo.com/76979871",
        thumbnail: "https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=800&q=80",
      },
      {
        id: "p2",
        title: "Teledysk — Nocny Kurs",
        category: "Music Video",
        role: "Director of Photography",
        video_url: "https://vimeo.com/76979871",
        thumbnail: "https://images.unsplash.com/photo-1518173946687-a4c8892bbd9f?auto=format&fit=crop&w=800&q=80",
      },
    ],
  },
  awards_strip: {
    heading: "Wyróżnienia & Festiwale",
    items: [
      { name: "Camerimage 2025", desc: "Oficjalna selekcja" },
      { name: "Fryderyk 2024", desc: "Nominacja — Teledysk Roku" },
      { name: "Grand Video Awards", desc: "Nagroda Główna w kategorii Branded Content" },
    ],
  },
  director_statement: {
    heading: "Podejście i Wizja",
    quote: "Kino to dla mnie przede wszystkim rytm, kontrast i autentyczność.",
    text: "Od ponad 8 lat realizuję projekty wideo dla czołowych marek i artystów w Polsce i za granicą. Łączę rzemiosło operatorskie z narracją fabularną.",
    signature: "Jan Kowalski",
  },
  minimal_contact: {
    heading: "Porozmawiajmy o projekcie",
    subheading: "Dostępność: realizacje komercyjne, teledyski, etiudy i filmy dokumentalne.",
    phone: "+48 600 700 800",
    email: "kontakt@tworcafilmowy.pl",
    instagram: "https://instagram.com/",
    vimeo: "https://vimeo.com/",
    location: "Warszawa · Dostępny na całym świecie",
  },
  quick_hero: {
    badge: "Dostępny od zaraz",
    title: "Usługi Elektryczne — Szybko i Solidnie",
    subtitle: "Kompleksowe instalacje, pomiary i usuwanie awarii.",
    city: "Poznań i okolice",
    phone: "+48 600 700 800",
    whatsapp: "+48600700800",
    cta_primary_text: "Zadzwoń teraz",
    cta_secondary_text: "Napisz na WhatsApp",
  },
  key_features: {
    heading: "Dlaczego warto?",
    items: [
      {
        title: "Ekspresowy dojazd",
        desc: "W nagłych awariach jesteśmy na miejscu w 60 minut.",
        icon: "bolt",
      },
      {
        title: "Uprawnienia SEP",
        desc: "Pełne uprawnienia dozoru i eksploatacji, protokoły do ubezpieczenia.",
        icon: "check",
      },
      {
        title: "Gwarancja i faktura",
        desc: "Darmowa wycena przed rozpoczęciem prac, faktury VAT 23%.",
        icon: "shield",
      },
    ],
  },
  quick_contact_card: {
    heading: "Skontaktuj się bezpośrednio",
    company_name: "Elektro-Fach Poznań",
    address: "ul. Dąbrowskiego 45",
    city: "60-842 Poznań",
    phone: "+48 600 700 800",
    email: "kontakt@elektrofach.pl",
    hours: "Poniedziałek – Sobota: 7:00 – 21:00\nPogotowie awaryjne: 24/7",
    booking_url: "",
  },
  faq_simple: {
    heading: "Często zadawane pytania",
    items: [
      { question: "Jak szybko możecie przyjechać?", answer: "W przypadku awarii zazwyczaj dojeżdżamy w ciągu 45-60 minut." },
      { question: "Czy wycena jest płatna?", answer: "Wstępna wycena telefoniczna jest całkowicie bezpłatna." },
    ],
  },
  testimonials_grid: {
    heading: "Co mówią nasi klienci",
    items: [
      { name: "Anna K.", text: "Profesjonalna obsługa i szybki termin. Zdecydowanie polecam!", rating: 5 },
      { name: "Marek W.", text: "Solidna robota, wysoka jakość i przejrzyste zasady współpracy.", rating: 5 },
      { name: "Katarzyna M.", text: "Bardzo dobry kontakt i terminowa realizacja projektu.", rating: 5 },
    ],
  },
  faq_accordion: {
    heading: "Najczęściej zadawane pytania",
    items: [
      { question: "Jak wygląda proces współpracy?", answer: "Na początku ustalamy zakres prac i termin, a następnie przedstawiamy bezpłatną wycenę." },
      { question: "Jaki jest standardowy czas realizacji?", answer: "Standardowy termin wynosi od 3 do 7 dni roboczych, w zależności od skali projektu." },
      { question: "Czy wystawiacie fakturę VAT?", answer: "Tak, do każdego zlecenia wystawiamy pełną fakturę VAT 23%." },
    ],
  },
  pricing_tiers: {
    heading: "Przejrzysty cennik",
    subheading: "Wybierz pakiet dopasowany do Twoich potrzeb. Bez ukrytych opłat.",
    items: [
      {
        name: "Pakiet Podstawowy",
        price: "199 zł",
        period: "",
        features: ["Wstępna konsultacja", "Szybka wycena w 24h", "Gwarancja jakości"],
        highlighted: false,
        cta_text: "Wybierz pakiet",
      },
      {
        name: "Pakiet Profesjonalny",
        price: "499 zł",
        period: "",
        features: ["Wszystko z Podstawowego", "Priorytetowy termin", "Protokół i raport", "Gwarancja 24 miesiące"],
        highlighted: true,
        cta_text: "Najpopularniejszy",
      },
      {
        name: "Pakiet Indywidualny",
        price: "Wycena",
        period: "indywidualna",
        features: ["Kompleksowa obsługa", "Dedykowany opiekun", "Wsparcie posprzedażowe", "Elastyczne warunki"],
        highlighted: false,
        cta_text: "Skontaktuj się",
      },
    ],
  },
  trust_stats: {
    heading: "Liczby, które mówią same za siebie",
    subheading: "Konkretne rezultaty i wieloletnie doświadczenie",
    items: [
      { value: "10+", label: "Lat doświadczenia", desc: "Na rynku usług" },
      { value: "500+", label: "Zrealizowanych zleceń", desc: "Dla klientów indywidualnych i firm" },
      { value: "100%", label: "Zadowolonych klientów", desc: "Gwarancja jakości i terminowości" },
      { value: "24h", label: "Czas reakcji", desc: "Szybki kontakt i wycena" },
    ],
  },
  services_list: {
    heading: "Nasze Usługi",
    subheading: "Wybierz usługę dopasowaną do Twoich potrzeb",
    items: [
      { title: "Usługa Podstawowa", desc: "Szybka realizacja i standardowy zakres prac", price: "od 150 zł", duration: "60 min" },
      { title: "Usługa Kompleksowa", desc: "Pełne wykonanie, materiały i gwarancja", price: "od 350 zł", duration: "120 min" },
      { title: "Konsultacja i Diagnoza", desc: "Dojazd, sprawdzenie i kosztorys na miejscu", price: "Bezpłatnie", duration: "30 min" },
    ],
  },
  booking_cta: {
    badge: "Dostępne terminy w tym tygodniu",
    heading: "Zarezerwuj dogodny termin już teraz",
    subheading: "Umów wizytę w kilka sekund bez czekania na telefon.",
    button_text: "Zarezerwuj wizytę",
    booking_url: "#kontakt",
    phone: "+48 600 700 800",
    note: "Bezpłatne odwołanie do 24h przed wizytą",
  },
  location_map: {
    heading: "Nasza Lokalizacja",
    subheading: "Odwiedź nas stacjonarnie lub sprawdź dojazd",
    address: "ul. Przykładowa 12, 60-100 Poznań",
    city: "Poznań",
    phone: "+48 600 700 800",
    hours: "Poniedziałek – Piątek: 8:00 – 18:00\nSobota: 9:00 – 14:00",
    map_embed_url: "",
  },
  gallery_grid: {
    heading: "Galeria Realizacji",
    subheading: "Zobacz efekty naszej pracy na fotografiach",
    feed_source: { type: "manual", handle: "", folder_id: "" },
    items: [
      { url: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80", title: "Precyzja i jakość", category: "Montaż" },
      { url: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80", title: "Nowoczesne rozwiązania", category: "Projekt" },
      { url: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80", title: "Dbałość o detale", category: "Realizacja" },
      { url: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80", title: "Komfortowa przestrzeń", category: "Wnętrza" },
    ],
  },
  google_reviews: {
    heading: "Opinie z Profilu Google",
    place_name: "",
    place_id: "",
    place_query: "",
    rating: null,
    reviews_count: 0,
    user_ratings_total: 0,
    write_review_url: "",
    items: [],
  },
  client_logos_grid: {
    heading: "Zaufali nam liderzy branży",
    subheading: "Partnerzy technologiczni i globalni klienci",
    items: [
      { id: "l1", name: "Emirates Group", logo_url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=300&q=80", website: "https://emirates.com" },
      { id: "l2", name: "Marriott International", logo_url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=300&q=80", website: "https://marriott.com" },
      { id: "l3", name: "Accor Hotels", logo_url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=300&q=80", website: "https://accor.com" },
      { id: "l4", name: "Invia Group", logo_url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=300&q=80", website: "https://invia.com" },
      { id: "l5", name: "FTI Touristik", logo_url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=300&q=80", website: "https://fti.de" },
      { id: "l6", name: "DerbySoft", logo_url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=300&q=80", website: "https://derbysoft.com" },
    ],
  },
  careers_board: {
    heading: "Dołącz do naszego zespołu",
    subheading: "Budujemy technologie jutra na styku travel i inżynierii danych",
    intro_text: "Szukamy pasjonatów wysokiej wydajności, optymalizacji i skalowalnych systemów chmurowych.",
    apply_email: "career@anixe.pl",
    items: [
      {
        id: "job1",
        title: "Senior C# / .NET Software Engineer",
        department: "Core Engineering",
        location: "Wrocław · Hybrydowo / Remote",
        type: "Pełny etat",
        salary: "18 000 – 25 000 PLN B2B",
        description: "Projektowanie i rozwój silników rezerwacyjnych o niskich opóźnieniach (Resfinity IBE), przetwarzających miliony transakcji dziennie.",
        requirements: "5+ lat w C#/.NET, znajomość architektur rozproszonych, multithreading i optymalizacji pamięci.",
      },
      {
        id: "job2",
        title: "Samodzielna Księgowa / Samodzielny Księgowy",
        department: "Finance & Operations",
        location: "Wrocław (biuro)",
        type: "Pełny etat",
        salary: "B2B / UoP",
        description: "Prowadzenie pełnej księgowości spółki technologicznej, rozliczenia międzynarodowe, raportowanie zarządcze.",
        requirements: "Doświadczenie w pełnej księgowości, znajomość przepisów podatkowych CIT/VAT, dokładność.",
      },
      {
        id: "job3",
        title: "Hotel Dynamic Sourcing Specialist",
        department: "Product & Sourcing",
        location: "Wrocław / Remote",
        type: "Pełny etat",
        salary: "Konkurencyjne",
        description: "Zarządzanie integracjami z dostawcami hotelowymi (bedbanks, wholesalers) oraz optymalizacja mapowania pokoi.",
        requirements: "Znajomość branży travel tech, standardów XML/JSON API hotelowych, analityczny umysł.",
      },
    ],
  },
  blog_showcase: {
    heading: "Aktualności & Baza Wiedzy",
    subheading: "Ostatnie wydarzenia, wyróżnienia i wdrożenia technologiczne",
    items: [
      {
        id: "post1",
        title: "ANIXE na ITB Berlin 2026 — przyszłość agregacji hoteli",
        category: "Wydarzenia",
        date: "2026-03-12",
        author: "ANIXE Team",
        cover_image: "https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=800&q=80",
        excerpt: "Prezentacja najnowszej generacji silnika Resfinity IBE na wiodących targach branży turystycznej w Berlinie.",
        content: "Tegoroczna edycja ITB Berlin była dla nas wyjątkowa. Pokazaliśmy nową architekturę akceleratorów wyszukiwania, która redukuje czas odpowiedzi zapytań o dostępność pokoi do poniżej 50 milisekund przy skali setek milionów zapytań dziennie.",
      },
      {
        id: "post2",
        title: "Holidaymine dołącza do ekosystemu ANIXE",
        category: "Partnerstwa",
        date: "2026-06-03",
        author: "Product Team",
        cover_image: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=800&q=80",
        excerpt: "Nowe globalne partnerstwo rozszerza możliwości dynamicznego zaopatrzenia hotelowego na rynkach azjatyckich.",
        content: "Z radością ogłaszamy nawiązanie strategicznego partnerstwa z platformą Holidaymine. Dzięki integracji z API Resfinity, nasi partnerzy zyskują dostęp do nowych baz łóżkowych z gwarancją najwyższej precyzji mapowania cen i dostępności.",
      },
      {
        id: "post3",
        title: "Wyróżnienie Forbes Diamonds oraz Magellan Award dla ANIXE",
        category: "Nagrody",
        date: "2025-11-20",
        author: "Zarząd ANIXE",
        cover_image: "https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?auto=format&fit=crop&w=800&q=80",
        excerpt: "Kolejne prestiżowe wyróżnienia biznesowe i technologiczne potwierdzają pozycję lidera innowacji travel.",
        content: "Zostaliśmy docenieni przez kapitułę Travel Weekly Magellan Awards za innowacyjność w automatycznym mapowaniu pokoi i optymalizacji przychodów (Yield Optimisation), a także znaleźliśmy się w gronie Diamentów Forbesa.",
      },
    ],
  },
  b2b_lead_scheduler: {
    heading: "Porozmawiajmy o skalowaniu Twojego biznesu",
    subheading: "Skontaktuj się z naszym zespołem inżynierów lub umów bezpośrednią demonstrację",
    email: "sales@anixe.pl",
    phone: "+48 71 364 79 50",
    address: "ul. Grabiszyńska 241b, 53-234 Wrocław, Poland",
    booking_url: "https://outlook.office365.com/book/anixe@anixe.pl/",
    booking_cta_text: "Umów 30-minutowe demo",
    form_heading: "Napisz do nas bezpośrednio",
    form_button_text: "Wyślij zapytanie",
    notification_email: "sales@anixe.pl",
  },
  mega_navbar: {
    brand_name: "ANIXE",
    brand_tagline: "Digital Travel & Commerce",
    cta_text: "Book a Demo",
    cta_url: "#spotkanie",
    menu_groups: [
      {
        id: "products",
        label: "Products",
        items: [
          { title: "Resfinity IBE", desc: "Silnik rezerwacji hoteli i pakietów", href: "#produkty", icon: "⚡" },
          { title: "Dynamic Sourcing", desc: "Agregacja globalnych dostawców hotelowych", href: "#produkty", icon: "🌐" },
          { title: "Cache Data Exports", desc: "Błyskawiczne akceleratory wyszukiwania", href: "#produkty", icon: "🚀" },
          { title: "Hotel & Room Mapping", desc: "Automatyczne mapowanie pokoi i stawek", href: "#produkty", icon: "🗺️" },
          { title: "Yield Optimiser", desc: "Maksymalizacja marży po sprzedaży", href: "#produkty", icon: "📈" },
        ],
      },
      {
        id: "solutions",
        label: "Solutions",
        items: [
          { title: "Airlines", desc: "Wzbogać ofertę lotów o hotele", href: "#rozwiazania", icon: "✈️" },
          { title: "Tour Operators", desc: "Automatyzacja pakietowania dynamicznego", href: "#rozwiazania", icon: "🏖️" },
          { title: "Online Travel Agencies (OTA)", desc: "Skalowalność pod wysoki ruch", href: "#rozwiazania", icon: "💻" },
          { title: "DMCs & Bedbanks", desc: "Dystrybucja i zarządzanie kontraktami", href: "#rozwiazania", icon: "🏨" },
        ],
      },
      {
        id: "company",
        label: "Company",
        items: [
          { title: "O nas & Nagrody", desc: "20+ lat inżynierii technologicznej", href: "#nagrody", icon: "🏆" },
          { title: "Kariera (Jobs)", desc: "Dołącz do zespołu we Wrocławiu", href: "#kariera", icon: "💼" },
          { title: "Aktualności & Blog", desc: "Wydarzenia, ITB Berlin, artykuły", href: "#aktualnosci", icon: "📰" },
        ],
      },
    ],
  },
};
